/* tslint:disable */
/* eslint-disable */
/**
 * sabino-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ProductReadDto,
} from '../models/index';
import {
    ProductReadDtoFromJSON,
    ProductReadDtoToJSON,
} from '../models/index';

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     */
    async getProductsAsyncRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ProductReadDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/products`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProductReadDtoFromJSON));
    }

    /**
     */
    async getProductsAsync(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ProductReadDto>> {
        const response = await this.getProductsAsyncRaw(initOverrides);
        return await response.value();
    }

}
